### ISSUE TITLE
varnish container build superfluos - use config feature

### ISSUE THREAD

**Issue by jensens** [plone/cookieplone-templates#157]
Why build an image if things are much simpler? 
In docker one can use configs like so:

```yaml
configs:
  varnishvcl:
    name: myproject-v1-varnish.vcl
    file: ./varnish/etc/varnish.vcl
# ...
services:
# ... 
  varnish:
    image: varnish:7.6
    configs:
      - source: varnishvcl
        target: /etc/varnish/default.vcl
```
