### ISSUE TITLE
Update the version of hook "check-python-versions" to support python 3.12 and 3.13 in pre-commit.yaml

### ISSUE THREAD

**Issue by kittauri** [plone/cookieplone-templates#166]
@ericof @davisagli 

In the ```.pre-commit-config.yaml``` in the backend is a hook which fails because of unsupported python versions.

## Code

```yaml
-   repo: https://github.com/mgedmin/check-python-versions
    rev: "0.21.3"
    hooks:
    -   id: check-python-versions
        args: ['--only', 'setup.py,pyproject.toml']
```

## Solution

Change Version from ```0.21.3``` to ```0.22.1``` as latest version adds support for Python 3.12 and 3.13 which Plone 6.1 can use.
