### ISSUE TITLE
github workflow of a backend add-on  fail

### ISSUE THREAD

**Issue by gil-cano** [plone/cookieplone-templates#229]
**Invalid workflow file**: .github/workflows/ci.yml#L69
The workflow is not valid. .github/workflows/ci.yml (Line: 69, Col: 23): Unrecognized named-value: 'env'. Located at position 1 within expression: env.PYTHON_VERSION .github/workflows/ci.yml (Line: 70, Col: 22): Unrecognized named-value: 'env'. Located at position 1 within expression: env.PLONE_VERSION

**Comment by gil-cano** [comment]
I guess the last two lines must be set to matrix

```
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: {{ cookiecutter.__gha_python_versions }}
        plone-version: {{ cookiecutter.__gha_plone_versions }}
    env:
      PYTHON_VERSION: {{ "${{ env.PYTHON_VERSION }}" }}
      PLONE_VERSION: {{ "${{ env.PLONE_VERSION }}" }}
```

**Comment by davisagli** [comment]
@gil-cano I just generated a backend addon and it has

```
    env:
      PYTHON_VERSION: ${{ env.PYTHON_VERSION }}
      PLONE_VERSION: ${{ env.PLONE_VERSION }}
```

I wonder if you have an old version of cookiecutter or something. How are you running cookieplone? I recommend doing it using `uvx` to make sure that it runs from its own virtualenv with up to date dependencies installed.

**Comment by gil-cano** [comment]
@davisagli sorry, I don't explain me clearly.

I run `uvx cookieplone backend_addon`, the `ci.yml` file as you said has:

```
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
        plone-version: ['6.1-latest', '6.0-latest']
    env:
      PYTHON_VERSION: ${{ env.PYTHON_VERSION }}
      PLONE_VERSION: ${{ env.PLONE_VERSION }}
```

When i push to github, it say the workflow is not valid.

```
unrecognized named-value: 'env' within expression: env.PYTHON_VERSION.
```

I replace `env` whit `matrix` in PYHON and PLONE expresions and now github status is success.
If that is correct, I can fix the template.

**Comment by davisagli** [comment]
@ericof Can you take a look here?

**Comment by ericof** [comment]
@gil-cano Clearly there is a typo there.

Please, change it to:

```yaml
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
        plone-version: ['6.1-latest', '6.0-latest']
    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
      PLONE_VERSION: ${{ matrix.plone-version }}
```
